version: '3.7'

services:
  booksmanagement-db:
    image: postgres
    restart: always
    ports:
      - '42921:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev_booksmanagement
    volumes:
      - booksmanagement-data:/var/lib/postgresql/data
        
volumes:
  booksmanagement-data:
